version: "2"
services:
  app:
    container_name: flask-app
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
  db:
    container_name: mysql-db
    image: mysql:5.7
    environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
            MYSQL_HOST: localhost
            MYSQL_DATABASE: FLASK
    ports:
      - "3308:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
